name: Publish NPM Packages

on:
  push:
    tags:
      - 'stubmock-v*.*.*'

jobs:
#  publish-stubmock-utils:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#
#      - uses: actions/setup-node@v1
#        with:
#          node-version: 16
#          registry-url: https://registry.npmjs.org/
#
#      - run: |
#          cd packages/stubmock-utils
#          npm publish
#        env:
#          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

  publish-stubmock:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - run: |
          cd packages/stubmock-core
          yarn install
          yarn build
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
